version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: pip
    directory: "/{{cookiecutter.project_slug}}"
    schedule:
      interval: daily
    versioning-strategy: lockfile-only
    allow:
      - dependency-type: "all"
