[tool.poetry]
name = "{{cookiecutter.project_name}}"
version = "0.1.0"
description = "{{cookiecutter.project_description}}"
authors = ["{{cookiecutter.author}}"]
license = "{{cookiecutter.license}}"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.78.0"
uvicorn = "^0.17.6"
pydantic = {extras = ["email", "dotenv"], version = "^1.9.1"}
fastapi-users = "^10.0.6"
{% if cookiecutter.database == "Tortoise" -%}
tortoise-orm = {extras = ["asyncpg"], version = "^0.19.1"}
fastapi-users-tortoise = "^0.2.0"
{% endif -%}
{% if cookiecutter.database == "Beanie" -%}
fastapi-users = {extras = ["beanie"], version = "^10.0.7"}
tortoise-orm = {extras = ["asyncpg"], version = "^0.19.1"}
{% endif -%}
aerich = "^0.6.3"
arq = "^0.22"
{% if cookiecutter.mail_service == 'Other SMTP' -%}
aiosmtplib = "^1.1.6"
{% endif -%}
python-multipart = "^0.0.5"
{% if cookiecutter.use_sentry == 'y' -%}
sentry-sdk = "^1.5.12"
redis = "^4.3.3"
{% endif -%}
rich = "^12.4.4"
typer = "^0.4.1"
watchgod = "^0.8.2"
Jinja2 = "^3.1.2"
httpx = "^0.23.0"
{% if cookiecutter.mail_service == 'Amazon SES' -%}
aioaws = "^0.13"
{% endif %}
[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
factory-boy = "^3.2.1"
pre-commit = "^2.19.0"
mypy = "^0.960"
isort = "^5.10.1"
flake8 = "^4.0.1"
poetryup = "^0.8.0"
ipython = "^8.4.0"
aiosmtpd = "^1.4.2"

[tool.aerich]
tortoise_orm = "app.db.config.TORTOISE_ORM"
location = "./migrations"
src_folder = "./."

[tool.isort]
profile = "black"

[tool.mypy]
warn_unreachable = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true
ignore_missing_imports = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
